Repository DecodersCommunity/Decoders-Community, pull requests merged in 2021-10, with the labels that each got.

#1 Harshit Sharma
  README.md
Labels: good first issue, Hacktoberfest, Hactoberfest-accepted

#4 PrakharTandon-200104078
  Contributors/PrakharTandon-200104078.md
Labels: good first issue, Hacktoberfest, Hactoberfest-accepted

#10 VedPrakashTiwari-200104067
  Contributors/VedPrakashTiwari-200104067.md
  README.md
Labels: documentation, enhancement, Hacktoberfest, Hactoberfest-accepted

#12 Ishita Gupta 200104036
  Contributors/IshitaGupta-200104036.md
Labels: Hacktoberfest, Hactoberfest-accepted

#13 Aditi Singh 200104006
  Contributors/AditiSingh-200104006.md
Labels: Hacktoberfest, Hactoberfest-accepted

#11 AmartyaYadav-200108020.md
  Contributors/AmartyaYadav-200108020.md
Labels: Hacktoberfest, Hactoberfest-accepted

#7 Ayush Som 200108026
  Contributors/AyushSom-200108026.md
Labels: Hacktoberfest, Hactoberfest-accepted

#9 UnnatiKumari-200104063
  Contributors/UnnatiKumari-200104063.md
Labels: Hacktoberfest, Hactoberfest-accepted

#8 Utkarsh Dixit 200104064
  Contributors/UtkarshDixit-200104064.md
Labels: Hacktoberfest, Hactoberfest-accepted

#14 TusharBhatia-200104061
  Contributors/TusharBhatia-200104061.md
Labels: Hacktoberfest, Hactoberfest-accepted

#15 Abhinav Awasthi 200108076
  Contributors/AbhinavAwasthi-200108076.md
Labels: Hacktoberfest, Hactoberfest-accepted

#88 Ankur Bajpai 200104076
  Contributors/AnkurBajpai-200104076.md
Labels: Hacktoberfest, Hactoberfest-accepted

#89 Sonika Shah 200105024
  Contributors/SonikaShah-200105024.md
Labels: Hacktoberfest, Hactoberfest-accepted

#90 Anubhav Shukla 200103014
  Contributors/AnubhavShukla-200103014.md
Labels: Hacktoberfest, Hactoberfest-accepted

#92 Created UjjwalSingh-200104062.md
  Contributors/UjjwalSingh-200104062.md
Labels: Hacktoberfest, Hactoberfest-accepted

#93 Rohan Tyagi
  Contributors/RohanTyagi.md
Labels: Hacktoberfest, Hactoberfest-accepted

#94 NitinSharma-200104080
  Contributors/NitinSharma-200104080.md
Labels: Hacktoberfest, Hactoberfest-accepted

#95 commit-1
  Contributors/shashank-rai.md
Labels: Hacktoberfest, Hactoberfest-accepted

#96 Ayushi Srivastava 200108001
  Contributors/ayushi srivastava.md
Labels: Hacktoberfest, Hactoberfest-accepted
