Repository DecodersCommunity/Decoders-Community, pull requests merged in 2022-10, with the labels that each got.

#102 added KushagraGupta-210104070.md file in Contributors folder.
  Contributors/KushagraGupta-210104070.md
Labels: documentation, Hacktoberfest, Hactoberfest-accepted

#108 Narendra Mohan Pathak-210104033
  Contributors/Narendra Mohan Pathak-210104033.md
Labels: Hactoberfest-accepted

#107 PriyanshiDhanuka-210104040
  Contributors/PriyanshiDhanuka-210104040.md
Labels: hacktoberfest-accepted

#110 JanhviSingh-200013139051
  Contributors/JanhviSingh-200013139051.md
Labels: hacktoberfest-accepted

#112 Rajat Dixit 200112028
  RajatDixit-200112028
Labels: Hactoberfest-accepted

#105 Harsh Agarwal-2001044036
  Contributors/HarshAgarwal-200104036.md
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#116 Devansh-200101028
  Contributors/Devansh Singh
Labels: hacktoberfest-accepted

#118 Create KhushiAgarwal.md
  Contributors/KhushiAgarwal.md
Labels: Hacktoberfest, hacktoberfest-accepted

#129 PratibhaSingh-210104039
  Contributors/PratibhaSingh-210104039.md
Labels: Hacktoberfest, hacktoberfest-accepted

#122 Create Paridhi Gupta.md
  Contributors/Paridhi Gupta.md
Labels: Hacktoberfest, hacktoberfest-accepted

#123 Created Anushka Paul-16900120123.md
  Contributors/Anushka Paul-16900120123.md
Labels: Hacktoberfest, hacktoberfest-accepted

#135 Palak Agarwal - 1901220100071
  Contributors/PalakAgarwal-1901220100071
Labels: good first issue, Hacktoberfest, hacktoberfest-accepted

#126 shiwani kumari-210104049
  Contributors/Shiwanikumari-210104049.md
Labels: Hacktoberfest, hacktoberfest-accepted

#133 PranavPatil2003000083
  Contributors/PranavPatil2003000083.md
Labels: Hacktoberfest, hacktoberfest-accepted

#136 ShefaliTiwari-1901220100098
  Contributors/ShefaliTiwari-1901220100098.md
Labels: Hacktoberfest, hacktoberfest-accepted

#103 YashAgarwal-210108073
  Contributors/YashAgarwal-210108073.md
Labels: Hacktoberfest, hacktoberfest-accepted

#104 aryangupta-210108015.md
  Contributors/aryangupta-210108015.md
Labels: Hacktoberfest, hacktoberfest-accepted

#114 PranjalMishra-210108047
  Contributors/PranjalMishra-210108047.md
Labels: Hacktoberfest, hacktoberfest-accepted

#115 Create Ishan Singh-200112008
  Ishan Singh-200112008
Labels: Hacktoberfest, hacktoberfest-accepted

#117 ShivamSingh_200103060.md
  Contributors/ShivamSingh-200103060.md
  Contributors/Shivam_Singh_200103060.md
Labels: Hacktoberfest, hacktoberfest-accepted

#138 ShreyaVerma-210310217392
  Contributors/ShreyaVerma-210104050
Labels: Hacktoberfest, hacktoberfest-accepted

#120 Pranav Prakash Saxena-210104036
  Contributors/Pranav Prakash Saxena-210104036.md
Labels: Hacktoberfest, hacktoberfest-accepted

#143 Create Abhishek-kumar190104002
  Contributors/Abhishek-kumar190104002
Labels: Hacktoberfest, hacktoberfest-accepted

#142 Create SachinKumar-190104055
  Contributors/SachinKumar-190104055
Labels: Hacktoberfest, hacktoberfest-accepted

#121 Added my profile in the given format
  Contributors/TribhuvanMishra.md
Labels: Hacktoberfest, hacktoberfest-accepted

#124 DeepakKumar-20135035
  Contributors/DeepakKumar-20135035.md
Labels: Hacktoberfest, hacktoberfest-accepted

#140 Nitin kumar 200104042.md
  Contributors/nitinkumar-200104042.md
Labels: Hacktoberfest, hacktoberfest-accepted

#125 Create Ashish Kumar Prajapati.md
  Contributors/Ashish Kumar Prajapati.md
Labels: Hacktoberfest, hacktoberfest-accepted

#128 Create PranjalAgarwal.md
  Contributors/PranjalAgarwal.md
Labels: Hacktoberfest, hacktoberfest-accepted

#130 Sandesh Powar 2005000077
  Contributors/SandeshPowar-2005000077.md
Labels: Hacktoberfest, hacktoberfest-accepted

#144 TannisthaBiswas-20010304.MD
  Contributors/TannisthaBiswas-20010304.MD.md
Labels: Hacktoberfest, hacktoberfest-accepted

#131 Addes Amit-Das.md
  Contributors/AmitDas-11700120062.md
Labels: Hacktoberfest, hacktoberfest-accepted

#132 for-loop
  for-loop.c
Labels: Hacktoberfest, hacktoberfest-accepted

#134 sourabhjadhav-2005000027
  Contributors/sourabhjadhav-2005000027.md
  robot.c++
Labels: Hacktoberfest, hacktoberfest-accepted

#137 210104037
  Contributors/Pranjal-210104037
Labels: Hacktoberfest, hacktoberfest-accepted

#139 chinmay.md
  Contributors/chinmay.md
Labels: Hacktoberfest, hacktoberfest-accepted

#141 Nitin kumar-200104042.md
  Contributors/NitinKumar-200104042.md
Labels: Hacktoberfest, hacktoberfest-accepted

#145 Arun Nayak
  Contributors/Arun Nayak.md
Labels: Hacktoberfest, hacktoberfest-accepted

#150 NitinSharma-200104080
  Contributors/3rd_NitinSharma-200104080.md
Labels: Hacktoberfest, hacktoberfest-accepted

#146 VedantSutar.md
  Contributors/C/1D Arrays in C.c
  Contributors/C/Array Reversal.c
  Contributors/C/Bitwise Operators.c
  Contributors/C/Boxes through a Tunnel.c
  Contributors/C/Calculate the Nth term.c
  Contributors/C/Conditional Statements in C.c
  Contributors/C/Digit Frequency.c
  Contributors/C/For Loop in C.c
  Contributors/C/Functions in C.c
  Contributors/C/Hello World  in C.c
  Contributors/C/Permutations of Strings.c
  Contributors/C/Playing With Characters.c
  Contributors/C/Pointers in C.c
  Contributors/C/Printing Pattern using Loops.c
  Contributors/C/Printing Tokens.c
  Contributors/C/README.md
  Contributors/C/Small Triangles - Large Triangles.c
  Contributors/C/Students Marks Sum.c
  Contributors/C/Sum and Difference of Two Numbers.c
  Contributors/C/Sum of Digits of a Five Digit Number.c
  Contributors/VedantSutar7649.md
Labels: Hacktoberfest, hacktoberfest-accepted

#151 MohitJaisal-190104041
  Contributors/MohitJaisal-190104041
Labels: documentation, Hacktoberfest, hacktoberfest-accepted

#153 template improvements
  README.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#154 Create Amol-01.md
  Contributors/Amol-01.md
Labels: Hacktoberfest, hacktoberfest-accepted
